name: CI

on:
  push:
    branches: 
      - 'dev/*'
  pull_request:
    branches: 
      - main

jobs:
  RunLinters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install cpplint
        run: pip install cpplint
        
      - name: Install cppcheck
        run: sudo apt install cppcheck
      
      - name: Check files
        run: python checkFiles.py

  Build:
    needs: [RunLinters]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building
        run: |
          cmake -DTEST=1 -B build
          cmake --build build
#         сюда команду с флагами

      - name: Upload our build dir
        uses: actions/upload-artifact@v3
        with:
          name: build-dir
          path: build

  RunTests:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download build dir
        uses: actions/download-artifact@v3
        with:
          name: build-dir
          path: build

      - name: Permissions for tests
        run: sudo chmod 777 ./build/tests/tests
      
      - name: Install valgrind
        run: sudo apt-get install valgrind

      - name: Test
        run: valgrind --tool=memcheck --leak-check=yes ctest -VV
        working-directory: build
    
      - name: Coverage install and run
        run: |
          sudo apt install lcov -y
          lcov -t "tests/tests" -o coverage.info -c -d tests/
          genhtml -o report coverage.info
        working-directory: build
      
      - name: Save coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ${{github.workspace}}/build/report
